services:
    
  server:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://admin:quickstart@postgres/quickstart
      - MAILHOG_HOST=mailhog
      - MAILHOG_PORT=1025
      - JWT_SECRET=replace_this_with_at_least_32_characters_long_secret
      - COOKIE_NAME=auth_session
      - COOKIE_DOMAIN=localhost
      - COOKIE_SECURE=false
      - SERVER_URL=http://server:3000
      - CORS_ORIGINS=http://localhost:5173
      - SESSION_DURATION=604800
   
  postgres:
    image: postgres:17
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: quickstart
      POSTGRES_DB: quickstart
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - 1025:1025
      - 8025:8025

volumes:
  postgres_data:
    name: quickstart_postgres_data
  minio_data: {}